base_url = "hhttps://iambort.io"
title = "IAmBort"
default_language = "en"
theme = "DeepThought"
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", fees = true, paginate_by = 10 },
]
languages = []
compile_sass = true
build_search_index = true
ignored_content = []
extra_syntaxes = []

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[translations]

[extra]
navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/posts", name = "Blog" },
        { url = "$BASE_URL/projects", name = "Projects" },
        { url = "$BASE_URL/tags", name = "Tags" },
        { url = "$BASE_URL/categories", name = "Categories" },
    ] },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "IAmBort"
avatar = "/images/avatar.png"

[extra.social]
github = "iambort"
#gitlab = "ratanshreshtha"
#keybase = "RatanShreshtha"
linkedin = "bart-carroll-8469056b"
#stackoverflow = "3728911"
email = "bart.a.carroll@gmail.com"
twitter = "iambort2"

[extra.analytics]
google = ""

[extra.commenting]
disqus = "deepthought-theme"

[extra.mapbox]
access_token = ""
